### ISSUE TITLE
Expected end of line in preprocessor expression

### ISSUE THREAD

**Issue by rupalitomar5** [firebase/quickstart-ios#424] opened 2018-02-22 10:44 UTC
I am getting this error in  Protobuf files , dependency of Firebase Messaging
![screen shot 2018-02-22 at 4 12 48 pm](https://user-images.githubusercontent.com/18718627/36534151-b8092efa-17eb-11e8-97d6-aa98d770fe9f.png)

**Comment by paulb777** [comment] 2018-02-22 16:38
Duplicate of https://github.com/firebase/firebase-ios-sdk/issues/836

**Closed by paulb777** 2018-02-22 16:38 UTC
