### ISSUE TITLE
Reuse Credential for Sign in with Apple

### ISSUE THREAD

**Issue by CodeTeamLabs** [firebase/quickstart-ios#931] opened 2020-03-13 23:37 UTC
Hi everyone when I use Sign in with Apple with Firebase everything works correctly .. The user is saved with the provider "Apple" .. I have a problem when I want to connect another provider to Apple because the apple credentials cannot be reused a second time in fact I get this message

> Duplicate credential received. Please try again with a new credential.

How can I get new credentials to create a firebase connection between another provider and Apple?

I tried to recover the new credentials from **error.userInfo** as it is written in the Firebase documentation but it always returns a Nil value .. how can I solve? code examples are really appreciated

This is my code

```
// Facebook Credential 
 let credential = FacebookAuthProvider.credential(withAccessToken: authToken)

   // Authentication for Facebook in Firebase with Credential
    Auth.auth().signIn(with: credential) { (authResult, errore) in

        if (errore != nil) {
            print("Error",errore!.localizedDescription)

            /* Firebase find the error with Facebook Authentication : 
               An account already exists with the same email address
               but different sign-in credentials. 
               Sign in using a provider associated with this email address. */

            if errore!._code == 17012 { // The code of previous error

                let tokenID = KeychainManager.getItemFromKeychain(forKey: AuthKey.applTokenID, keyPrefix: AuthKey.prefix)!
                let nonce = KeychainManager.getItemFromKeychain(forKey: AuthKey.applNonce, keyPrefix: AuthKey.prefix)

                // Apple Credential in Keychain
                let appleCredentials = OAuthProvider.credential(withProviderID: "apple.com", idToken: tokenID, rawNonce: nonce)

                Auth.auth().signIn(with: appleCredentials) { (authResult, error) in

                     if error != nil {
                       print(error!.localizedDescription)

                      /* Firebase find NEW error with Apple Authentication : 
                         Duplicate credential received. 
                         Please try again with a new credential. */

                     }

                     authResult?.user.link(with: credential, completion: { (_, error) in

                     /* The Link is not successful because Firebase 
                        cannot reuse Apple's credentials for a second time */
```

**Comment by bojeil-google** [comment] 2020-03-13 23:51
This works as intended to avoid replay attacks. When an account already exists with the same email address, you can get an [updated credential](https://firebase.google.com/docs/reference/swift/firebaseauth/api/reference/Constants#/c:@FIRAuthErrorUserInfoUpdatedCredentialKey) from the `NSError` userinfo dictionary.

**Comment by CodeTeamLabs** [comment] 2020-03-13 23:55
> This works as intended to avoid replay attacks. When an account already exists with the same email address, you can get an [updated credential](https://firebase.google.com/docs/reference/swift/firebaseauth/api/reference/Constants#/c:@FIRAuthErrorUserInfoUpdatedCredentialKey) from the `NSError` userinfo dictionary.

hello and thanks for your help ... I tried to use error.userInfo but it always gave a Nil value ... maybe I did something wrong when I wrote the code .. could you give me an example of code to recover a new credential using the so and what I entered above? at least I can understand where I went wrong with error.userInfo

**Comment by bojeil-google** [comment] 2020-03-14 00:00
This [snippet](https://firebase.google.com/docs/auth/ios/microsoft-oauth#handling-account-exists-with-different-credential-errors) may be helpful.

**Comment by CodeTeamLabs** [comment] 2020-03-14 00:24
> This [snippet](https://firebase.google.com/docs/auth/ios/microsoft-oauth#handling-account-exists-with-different-credential-errors) may be helpful.


I tried to follow the link you recommended (very nice) when I run the code my app crashes with this..

I tried with both facebook and apple but in both cases the error is always the same, it only replaces the provider

```
NSAssert(![providerID isEqual:@"apple.com"],
           @"Sign in with Apple is not supported via generic IDP; You must use the Apple iOS SDK"
           " for Sign in with Apple.");
```

-----

```
NSAssert(![providerID isEqual:FIRFacebookAuthProviderID],
           @"Sign in with Facebook is not supported via generic IDP; the Facebook TOS "
           "dictate that you must use the Facebook iOS SDK for Facebook login.");
```

**Comment by CodeTeamLabs** [comment] 2020-03-14 01:08
> This [snippet](https://firebase.google.com/docs/auth/ios/microsoft-oauth#handling-account-exists-with-different-credential-errors) may be helpful.


Surely I'm wrong the position in which to insert the request for the new credential because I keep getting errors ... If I log in with facebook and when it finds the error of "same email for the user" I immediately access apple and here it also returns me the error of the credentials at this point use `let pendingCred = (error! as NSError) .userInfo [AuthErrorUserInfoUpdatedCredentialKey] as! AuthCredential`
to retrieve the new credentials .. immediately my app crashes because 
**AuthErrorUserInfoUpdatedCredentialKey** is **Nil** ..

I really don't understand where I'm wrong ... sorry for these idiotic questions but I'm confused

**Comment by CodeTeamLabs** [comment] 2020-03-14 09:27
in this case I shouldn't use `provider.getCredential` but rather `signInWithCredential` I understand correctly ?? just for facebook and apple should i do this... 

forgive me if I'm talking too much about this question but I haven't been able to solve this process for 2 days

**Comment by CodeTeamLabs** [comment] 2020-03-14 10:22
> This [snippet](https://firebase.google.com/docs/auth/ios/microsoft-oauth#handling-account-exists-with-different-credential-errors) may be helpful.

In the documentation that bojeil-google advised me to follow, the user is authenticated with the provider EmailAuthProviderID, obviously using EmailAuthProviderID I think this is only an example but if instead this would be the right way to go to authenticate the user I would have the same problem because during authentication with apple I cannot recover the user's password so I could not log in anyway ...

How do I get over this block to complete the connection between the two providers?

```
Auth.auth().signIn(with: FacebookAuthProvider.credential(withAccessToken: authToken)) { authResult, error in
    if error != nil {
      // Handle error.
        if (error as NSError?)?.code == AuthErrorCode.accountExistsWithDifferentCredential.rawValue {
            // Get pending credential and email of existing account.
            let existingAcctEmail = (error! as NSError).userInfo[AuthErrorUserInfoEmailKey] as! String
            let pendingCred = (error! as NSError).userInfo[AuthErrorUserInfoUpdatedCredentialKey] as! AuthCredential
            
            Auth.auth().fetchSignInMethods(forEmail: existingAcctEmail) { (methods, error) in
                print(methods!)
                if (methods?.contains("apple.com"))! {
                    
                    // **** This Flow stops here because I can't reuse Apple's credentials a second time. *****
                    
                    Auth.auth().signIn(with: appleCredential) { user, error in
                        if user != nil {
                          // Link pending credential to account.
                          Auth.auth().currentUser?.link(with: pendingCred) { result, error in
                            // ...
                        
                            }
                        }
                    }
                }
            }
        }
    }
```

**Comment by CodeTeamLabs** [comment] 2020-03-14 14:07
Obviously in all this I want to specify in my case the user has never created an account within my app with EmailAuthProviderID provider .. so I'm only talking about access via external providers Facebook ---> Apple

**Comment by CodeTeamLabs** [comment] 2020-03-15 21:29
@bojeil-google  any ideas?

**Comment by ncooke3** [comment] 2020-07-01 16:02
Hi @CodeTeamLabs, is this still an issue for you? To confirm, after authenticating an account with Sign in with Apple, you would like to link the account with another provider like Facebook, etc? Let me know, and I can try to help! 🙂

**Comment by carlplaylab** [comment] 2020-08-06 16:43
Having the same issue where I get a token and nonce from apple sign in, link them on a firebase user, and get an error (duplicate credential exception) when linking to my current firebase user. This is possible due to my apple id being used on another firebase user account?

To proceed, must I get a new Apple sign in credentials before tring a new firebase auth sign in?

**Comment by morganchen12** [comment] 2020-08-06 17:09
@carlplaylab in your use case the updated credential should be present in the account linking error's userInfo dictionary.

**Comment by Robin-Gad** [comment] 2020-11-13 23:45
Это первый файл который сюда скачал

**Comment by morganchen12** [comment] 2020-11-14 00:34
Hey all, closing this since it hasn't had any new activity from the original commenter.

**Closed by morganchen12** 2020-11-14 00:34 UTC
