### ISSUE TITLE
Firebase Messaging QS - TIC TCP Conn Failed in iOS 11

### ISSUE THREAD

**Issue by dbrgs** [firebase/quickstart-ios#309] opened 2017-07-28 13:49 UTC
After compilation (xCode 9 - Beta 4) of the Firebase Messaging QS code sample, on the run of the sample on a device running (iOS 11 - Beta 4) we receive the following error.

MessagingExampleSwift[354:15228] TIC TCP Conn Failed [1:0x1c4361e00]: 1:50 Err(50)
MessagingExampleSwift[354:15228] Task <FCE99415-AFCB-4F75-9DAF-6FBC0FBC8BF0>.<1> HTTP load failed (error code: -1009 [1:50])
MessagingExampleSwift[354:15226] Task <FCE99415-AFCB-4F75-9DAF-6FBC0FBC8BF0>.<1> finished with error - code: -1009

Running the same code on a device running (iOS 10.3) does not receive the error.   

The result is that we cannot retrieve an FCM Token correctly.

We are receiving the same issue on our own application, which is why we downloaded and tested against the sample in the first place.

Any help would be greatly appreciated.

**Comment by morganchen12** [comment] 2017-07-28 16:57
@rsattar is this a known issue?

**Comment by kpiascik** [comment] 2017-08-09 12:33
This is with Swizzling DISABLED.

**Comment by rsattar** [comment] 2017-08-14 18:58
Hmm, I've tested both the quick start sample apps (Obj-C and Swift) on iOS 11 (beta 6, with Xcode 9 beta 5), and both are working for me.

FYI, error `-1009` is [NSURLErrorNotConnectedToInternet](https://developer.apple.com/documentation/foundation/nsurlerrornotconnectedtointernet), so I'm guessing it's a state issue on your device. Perhaps Airplane Mode is active? 

Closing the issue, but feel free to re-open if it's still happening and is reproducible. Thanks!

**Closed by rsattar** 2017-08-14 18:58 UTC

**Comment by kpiascik** [comment] 2017-08-15 12:17
@rsattar It used to not work when compiled with XCode 9 or XCode 8.  Now the problem is when compiling with XCode 8 only.

**Comment by rsattar** [comment] 2017-08-15 17:51
Hmm, so I can try and reproduce, you're saying that the quickstart-ios app in this repo doesn't work on Xcode 8? Which build of Xcode 8 did you try? And any particular iOS device I should test with?

Thanks!

**Comment by kpiascik** [comment] 2017-08-15 18:47
@rsattar XCode 8.3 built binary running on iOS 11 device.

**Comment by AhmedShammala** [comment] 2017-09-27 09:23
+1

**Comment by AhmedShammala** [comment] 2017-10-16 06:24
@dbrgs did you resolved this issue ?

**Comment by kpiascik** [comment] 2017-10-26 15:50
@AhmedShammala Yes, the issue turned out to be we were calling the old apnsToken API, which didn't work. 
Changing this:
`Messaging.messaging().setAPNSToken(deviceToken, type: .sandbox)`
to this:
`Messaging.messaging().apnsToken = deviceToken`
fixed our issue
