### ISSUE TITLE
Subscribing to multiple topics Fail

### ISSUE THREAD

**Issue by travoux** [firebase/quickstart-ios#8] opened 2016-05-22 09:31 UTC
Why am I getting <FIRMessaging/WARNING> Failed to subscribe to topic Error Domain=com.google.fcm Code=5 "(null)"

<img width="902" alt="screen shot 2016-05-22 at 5 26 36 pm" src="https://cloud.githubusercontent.com/assets/1425461/15453276/65819d68-2042-11e6-94ea-19c494600cec.png">

When subscribing to multiple topics. Since, there is no callback to queue multiple calls, we can only call in a loop like below

<img width="387" alt="screen shot 2016-05-22 at 5 30 52 pm" src="https://cloud.githubusercontent.com/assets/1425461/15453295/08e11cc2-2043-11e6-80e4-bfee87464807.png">

**Comment by kroikie** [comment] 2016-05-23 22:01
In this case are you eventually successfully subscribing to the topics, or does the subscription continue to fail? If a subscription is unsuccessful the library will retry.

**Comment by travoux** [comment] 2016-05-24 04:59
Subscription is failed and the user never received messages sent to that topic. Error happens immediately when the second call is made in the loop..

**Comment by kroikie** [comment] 2016-05-24 16:26
I am able to reproduce the error log message but I'm still able to receive the notifications sent to the topic.

Are you getting a {"message_id": <message-id>} response?

**Comment by travoux** [comment] 2016-05-25 06:10
I think yes, we did receive message_id. We will re-check this later since we rolled back the code.

**Comment by kroikie** [comment] 2016-05-29 17:43
Thanks for giving it a try, I'll close this issue then, but please file a new issue if you confirm that successfully sent messages are not being received on the client.

**Closed by kroikie** 2016-05-29 17:43 UTC

**Comment by Shoshin23** [comment] 2016-06-20 16:56
Just to contribute to this discussion. I get the same message while subscribing to multiple topics but the subscription goes through. I'm still concerned about this issue. Any pointers to fix this? Are there any methods in the API to check if a topic has been successfully subscribed to?

**Comment by martolini** [comment] 2016-08-06 12:16
I'm seconding this. When subscribing to multiple topics, the error codes comes up. There should be a `completion` callback or some kind of status so we could know whether it successfully subscribed or not.

**Comment by Shoshin23** [comment] 2016-08-07 12:06
The worst part about this is that it fails sometimes, it succeeds sometimes. So there's no way to know for sure which makes it all the more unnerving. The folks who subscribe to a topic sometimes get the PNs, sometimes they don't.

**Comment by olegdynamo** [comment] 2016-11-09 13:33
But why is this issue closed? I can see it all the way. If you loop through several topics with subscribeToTopic, you get the error: "<FIRMessaging/WARNING> Failed to subscribe to topic Error Domain=com.google.fcm Code=5". Moreover, if you loop through several topics with unsubscribeFromTopic, you get the same error..
Third, it feels so strange that there is no way to get the result from the subscribe/unsubscribe, e.g. via callback. So that one could act upon the error.

How to re-open the issue? Or should we create a new one?

**Comment by jacksonej** [comment] 2017-02-07 12:33
Why this issue closed?? Issue still in the latest library

**Comment by roeeAsaf** [comment] 2017-03-27 14:34
its happens me to !

**Comment by ElNinjaGaiden** [comment] 2017-06-22 00:14
This happens on iOS and even when you are not into a loop, just a single subscription request.

**Comment by rsattar** [comment] 2017-06-23 19:32
Hmm you should be seeing a code 5 issue when subscribing to topics (this code that generates a code 5 was removed). What exactly is the issue you're seeing? Could you post it as a separate issue?

**Comment by travoux** [comment] 2017-06-24 15:13
Sorry which version/commit has this fix? Got the latest and I still same error when subscribing to multiple topics!

**Comment by rsattar** [comment] 2017-06-26 20:35
@travoux This should be available since February this year (FirebaseMessaging 1.2.2). Can you share with me your console log that shows the code 5 for subscribing/unsubscribing to topics?

**Comment by ElNinjaGaiden** [comment] 2017-06-26 21:06
@rsattar I'm my case it seems the problem was a timing issue. I was trying to subscribe to a topic as soon as the `platform.ready` event was fired (I'm using Ionic).

I moved the code to call the subscription function later and it works fine. But just for the record I'm not subscribing to several topics at a time, just one, so I can't testify the other problem is fixed or not.

**Comment by Anujmoglix** [comment] 2018-05-03 08:49
Hi all ,
   I am getting issue Failed to fetch APNS token Error Domain=com.firebase.iid Code=1001 "(null)"
```
var myTopics = "all";
      this.fcm.subscribeToTopic(myTopics).then(success => {
          console.log("***Here is success****"+success); alert(success) },
              error => { console.log("***This is the issue****"+error); alert(error);})
          .catch(response => {
              alert(response);
              console.error('Gists error = ', response);
          });
```
