### ISSUE TITLE
Firebase Dynamic Links giving error when clicking on long link: Deep Link does not contain valid required params

### ISSUE THREAD

**Issue by sindhu238** [firebase/quickstart-ios#774] opened 2019-08-13 12:38 UTC
I have created dynamic links in firebase console and copy pasted long link to the email. 
But when I click on the link I get this error:
**Error Message:**
Deep Link does not contain valid required params. URL params: {
    apn = "com.app.android.xxx.xyz";
    ibi = "com.xxx.xyz";
    isi = 14xxxxxxx;
    link = "https://www.xxx.com/en/account/sign-in";
}

**Here is the link that i am clicking on:** 
https://app.xxx.com/deeplink/?link=https://www.xxx.com/en/account/sign-in&apn=com.app.xxx.xyz.etx&isi=14xxxxxxx&ibi=com.xxx.xyz

**Here is how I have setup for the dynamic links:**
<img width="1319" alt="Screenshot 2019-08-13 at 13 35 16" src="https://user-images.githubusercontent.com/17729158/62942027-539a1e80-bdcf-11e9-9377-0f3205b2adf5.png">

<img width="1365" alt="Screenshot 2019-08-13 at 13 35 35" src="https://user-images.githubusercontent.com/17729158/62942032-56950f00-bdcf-11e9-9e39-e584c7cfcce2.png">

**In AppDelegate:**
```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        FirebaseOptions.defaultOptions()?.deepLinkURLScheme = "applinks:app.xxx.com"
        FirebaseApp.configure()

}
```

And when i click on the deeplink: This function gets called:
```
 func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool {
        let handled = DynamicLinks.dynamicLinks().handleUniversalLink(userActivity.webpageURL!) { dynamiclink, error in
            print("dyn:: ------- \(dynamiclink?.url)")
        }

        return handled
    }
```

But handled will always return false and I see this error message in the console:
Deep Link does not contain valid required params

**Comment by ToddKerpelman** [comment] 2019-08-13 16:02
Have you tried some of the suggestions at https://firebase.google.com/docs/dynamic-links/debug (specifically, looking at the preview page and running the self-diagnostic form)

**Comment by sindhu238** [comment] 2019-08-14 10:29
@ToddKerpelman ,
Thanks for helping me debug. I could see this error when i try using the self-diagnostic tool:
---- Firebase Dynamic Links diagnostic output start ----
Firebase Dynamic Links framework version 4.0.1
System information: OS iOS, OS version 11.4, model iPhone
Current date 2019-08-14 10:23:26 +0000
Device locale en-GB (raw en_GB), timezone Europe/London
ERROR: Specified custom URL scheme is (null) but Info.plist do not contain such scheme in CFBundleURLTypes key.
	AppID Prefix: 8Wxxxxxxx, Team ID: 8WxxxxxxxL, AppId Prefix equal to Team ID: YES
performDiagnostic detected 1 ERRORS.
---- Firebase Dynamic Links diagnostic output end ----


**But In AppDelegate I had this:**
```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
FirebaseOptions.defaultOptions()?.deepLinkURLScheme = "com.xxx.xyz"
        FirebaseApp.configure()
}
```

**In Info.plist:**
<img width="755" alt="Screenshot 2019-08-14 at 11 28 19" src="https://user-images.githubusercontent.com/17729158/63014524-a5ea4680-be86-11e9-8276-27b7dc379c8e.png">

I have having the same custom url scheme in both Info.plist and AppDelegate.
Is there some thing else I am missing?

Thanks

**Comment by ToddKerpelman** [comment] 2019-08-16 00:03
Hmm... well, a few things I noticed reviewing this thread:

1. If your default customer URL scheme is just the reversed bundle ID, you don't need to  specify one at all. I would just stop trying to specify or define it, since that tends to do more harm than good.

2. I noticed in your earlier code, you had your deepLinkURLScheme as "applinks:com.xxx.xyz". If that was still the case, that "applinks" bit of your string might be messing it up.

3. (Most importantly) This might not actually be a problem at all, assuming your dynamic link is working the way it's supposed to. I found out that error is generated by the Analytics library, and it's basically telling you that it can't generate a proper campaign measurement from your Deep Link. Which, honestly, is probably working as intended, since you're not adding utm_ parameters to your link. I'm gonna see maybe if we can change that debug info, though, so it doesn't confuse people who run into it and think the entire link is bad.

That said, it's really hard to debug this with fake links and domains. (Particularly when they redirect you to porn sites.) Since this doesn't seem to be a problem with the quickstart, can I suggest that if you have any follow-up issues, that you send them directly to support so they can debug your real links? 

With that said, I'm going to close this issue for now.

**Closed by ToddKerpelman** 2019-08-16 00:03 UTC

**Comment by danieil** [comment] 2020-03-04 05:00
> I have created dynamic links in firebase console and copy pasted long link to the email.
> But when I click on the link I get this error:
> **Error Message:**
> Deep Link does not contain valid required params. URL params: {
> apn = "com.app.android.xxx.xyz";
> ibi = "com.xxx.xyz";
> isi = 14xxxxxxx;
> link = "https://www.xxx.com/en/account/sign-in";
> }
> 
> **Here is the link that i am clicking on:**
> https://app.xxx.com/deeplink/?link=https://www.xxx.com/en/account/sign-in&apn=com.app.xxx.xyz.etx&isi=14xxxxxxx&ibi=com.xxx.xyz
> 
> **Here is how I have setup for the dynamic links:**
> <img alt="Screenshot 2019-08-13 at 13 35 16" width="1319" src="https://user-images.githubusercontent.com/17729158/62942027-539a1e80-bdcf-11e9-9377-0f3205b2adf5.png">
> 
> <img alt="Screenshot 2019-08-13 at 13 35 35" width="1365" src="https://user-images.githubusercontent.com/17729158/62942032-56950f00-bdcf-11e9-9e39-e584c7cfcce2.png">
> 
> **In AppDelegate:**
> 
> ```
> func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
>         FirebaseOptions.defaultOptions()?.deepLinkURLScheme = "applinks:app.xxx.com"
>         FirebaseApp.configure()
> 
> }
> ```
> 
> And when i click on the deeplink: This function gets called:
> 
> ```
>  func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool {
>         let handled = DynamicLinks.dynamicLinks().handleUniversalLink(userActivity.webpageURL!) { dynamiclink, error in
>             print("dyn:: ------- \(dynamiclink?.url)")
>         }
> 
>         return handled
>     }
> ```
> 
> But handled will always return false and I see this error message in the console:
> Deep Link does not contain valid required params

FirebaseOptions.defaultOptions()?.deepLinkURLScheme = "applinks:app.xxx.com"
This should be written as follows
FirebaseOptions.defaultOptions()?.deepLinkURLScheme = "com.xxx.xyz"

**Comment by hardikamal** [comment] 2020-11-02 11:17
@sindhu238 Were you able to resolve the issue?
@ToddKerpelman I am also facing the same issue.

**Comment by mockturtl** [comment] 2022-05-11 02:31
@ToddKerpelman https://github.com/firebase/quickstart-ios/issues/774#issuecomment-521838393

> This might not actually be a problem at all, assuming your dynamic link is working the way it's supposed to. I found out that error is generated by the Analytics library, and it's basically telling you that it can't generate a proper campaign measurement from your Deep Link. Which, honestly, is probably working as intended, since you're not adding utm_ parameters to your link. **I'm gonna see maybe if we can change that debug info**, though, so it doesn't confuse people who run into it and think the entire link is bad.

Did you ever get a chance to make this change?

I'm hopeful I've finally sewn up the loose ends to get our campaigns working -- on round 5 of "guess we'll just see whether it works in prod."  I think it would have spared me much grief if the debug output said what you explained.  (Compare: _"Something is missing, :shrug:.  Did Firebase get the event?  Tune in tomorrow!"_)

Other doc suggestions, according to my current understanding of what I've missed:

- **Will my users need to grant IDFA/tracking permission for me to see iOS conversions in the Ads dashboard, or not?**
- TestFlight and the `ifl` param
- Does it matter if my marketing uses the "Short" vs "Long" link shown in Link Details?
- percent-encoding the `link` param

**Comment by speshiy** [comment] 2022-05-24 06:15
Hi!
I'm using Ionic and faced the same problem. 
I just ADD ifl param into url and it works

https://url.page.link/?link=https://open.url.com?promocode=PEt0wzqwcx&apn=com.app.app&isi=123456&ibi=com.app.app&**ifl=https://url**
