### ISSUE TITLE
FirebaseMessaging connectWithCompletion main thread dependency

### ISSUE THREAD

**Issue by daveanderson** [firebase/quickstart-ios#67] opened 2016-08-05 03:25 UTC
In using `FIRMessaging.messaging().connectWithCompletion` with the iOS 10 SDK and the `UNUserNotificationCenter.currentNotificationCenter().requestAuthorizationWithOptions` we are experiencing the following exception:

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'GIPReachability should be used from the main thread'
*** First throw call stack:
(0x18c0ab348 0x18aae855c 0x18c0ab21c 0x18cb30d20 0x100517fe0 0x1004fbacc 0x1004fb860 0x101a0921c 0x101a0a04c 0x1004fb7e4 0x1003f9ba0 0x1003f6e88 0x1003f639c 0x1001efc7c 0x101a0925c 0x101a0921c 0x101a16b54 0x101a0cce4 0x101a170f0 0x101a18e6c 0x101a18bb8 0x18b1412d8 0x18b140dc4)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

The `UNUserNotificationCenter.currentNotificationCenter().requestAuthorizationWithOptions` closure is _not_ called on the main thread. Thus making a call to `FIRMessaging.messaging().connectWithCompletion` directly within this closure results in the above exception.

Obviously we can work around this by dispatching to the main thread, before calling `FIRMessaging.messaging().connectWithCompletion` however the documentation for `connectWithCompletion` does not indicate this main-thread dependency.

Alternatively `connectWithCompletion` should _internally_ handle the main-thread dependency.

**Comment by kroikie** [comment] 2016-10-11 21:16
Hi @daveanderson sorry for the delayed response, is this still an issue for you. I'm not able to reproduce this, are you seeing this when running the sample directly from this repo?

**Comment by revolter** [comment] 2016-12-15 14:41
M neither, I added `dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_HIGH, 0), ^{` before the `connectWithCompletion:` call and it worked correctly.

**Comment by kroikie** [comment] 2016-12-16 19:04
Closing this issue since it seems to no longer be reproducible, open a new issue if this is still happening.

**Closed by kroikie** 2016-12-16 19:04 UTC
