### ISSUE TITLE
Firebase/DynamicLinks is opening a different env.

### ISSUE THREAD

**Issue by MireyaOrta** [firebase/quickstart-ios#1052] opened 2020-09-23 15:15 UTC
Hello, I started using `Firebase/DynamicLinks` in my project where I have 3 different environments `production`, `staging` and `development` each env has a different firebase project. 

Ever since we started using `Firebase/DynamicLinks` we will install production application while having staging application installed for example, and then the production version would launch but some time after the staging env would be launch and we end up with the wrong env open. 

in the beginning, it was happening every time I was building the app, then I updated the pod to the last version and now it's only happening the first time the app is installed in the phone, but if a user installs from testflight and has others env installed it ends up with the wrong env open.

**Comment by MireyaOrta** [comment] 2020-09-23 15:25
If I comment out `FIRDynamicLinks.m: checkForPendingDynamicLink` it stops happening. Could I get information on this bug, please?

**Comment by eldhosembabu** [comment] 2020-09-23 17:49
Hi @MireyaOrta ,

Thanks for your question. 

Since you mentioned you are having 3 different firebase projects for your env prod, staging and development, can you please confirm you are using different GoogleService-info.plist for each env specific apps?

Since you mentioned "the production version would launch but some time after the staging env would be launch", can you confirm the launch is triggered by clicking on an Firebase Dynamic Link? If yes, could you please share the dynamic link that you have used for testing along with the bundle ids of your prod, staging and development apps. Thanks

**Comment by danpecher** [comment] 2020-09-23 18:19
Hey @eldhosembabu, thanks for you response!

Yes, all three environments have their `.plist` file.

The steps to reproduce are 
1. Have the staging app installed.
2. Delete the production or dev app from the phone (it happens with both of them: if you open production -> it opens staging. If you open dev -> it opens staging).
3. Install production or development again.
4. Open the app.

The pending dynamic link retrieval gets triggered and the pod tries to open the app again (even though there is no dynamic link pending). 

The code gets all the way here:
<img width="1547" alt="Screenshot 2020-09-23 at 19 55 36" src="https://user-images.githubusercontent.com/2471616/94051107-5ee3ba00-fdd7-11ea-8bcb-8d8a80836485.png">

and apparently tries to open the non-existing dynamic link but opens the staging app instead.

**Comment by danpecher** [comment] 2020-09-24 08:03
Also, another information that might help:

We discovered the the `url` in this scenario is `com.company.app.dev://google/link/?dismiss=1&is_weak_match=1` and if we try to open that from our `AppDelegate`, it opens staging. If we try to open just `com.company.app.dev` nothing happens, which is correct.

**Comment by eldhosembabu** [comment] 2020-09-24 21:29
Thanks for your response and I assume that you are simply opening up the app after its being installed by clicking on the app icon.

During fresh start (first start after install) of the app, it is expected to check for any pending dynamic links to support deferred deeplinking. 

In the code picture you posted above, usually line no: 536 is the one which is expected to be called for iOS version 9 and above; but in your case, could you please check why line no: 541 is getting called? Are you testing in iOS version < 9 or is the application delegate is null?

Also If "com.company.app.dev://google/link/?dismiss=1&is_weak_match=1" opening up your staging app, then i think you are  using custom url schemes with "com.company.app.dev" in your staging app. Can you confirm on that too?

**Comment by morganchen12** [comment] 2022-03-08 22:17
Closing since this issue has staled.

**Closed by morganchen12** 2022-03-08 22:17 UTC
