### ISSUE TITLE
<FIRAnalytics/ERROR> Inconsistent state, raw event is expected

### ISSUE THREAD

**Issue by eelijah** [firebase/quickstart-ios#79] opened 2016-08-24 11:03 UTC
After `[FIRApp configure];` console print that:
<FIRAnalytics/DEBUG> Network status has changed. Code, status: 2, Connected
<FIRAnalytics/DEBUG> Timer scheduled to fire in approx. (s): -1890.133983075619
<FIRAnalytics/DEBUG> Upload task scheduled to be executed in approx. (s): -1890.133983075619
<FIRAnalytics/DEBUG> Timer fired
<FIRAnalytics/DEBUG> Canceling active timer
<FIRAnalytics/DEBUG> Starting data upload
<FIRAnalytics/ERROR> Inconsistent state, raw event is expected. Error: Error Domain=com.google.gmp.measurement.ErrorDomain Code=2 "Cannot create an event from database. Missing origin parameter" UserInfo={NSLocalizedDescription=Cannot create an event from database. Missing origin parameter}
<FIRAnalytics/ERROR> Transaction failed
<FIRAnalytics/DEBUG> No data to upload

And the Firebase console don't show any logs from app (even after 24 hours)
What does it mean and how fix it?

**Comment by vlider** [comment] 2016-09-07 16:18
I have the same issue from my IOS side. Could anybody help with resolving the error? What might be the problem? 
Thanks in advance

**Comment by baolocdo** [comment] 2016-09-27 15:30
eelijah@, vlider@: Which iOS version are you running on? Have you updated to the new Firebase Analytics pod? If so, which version of the pod? If you remove the app and reinstall, does the problem still persist? Thank you.

**Comment by eelijah** [comment] 2016-10-26 11:55
<FIRAnalytics/DEBUG> Starting data upload
<FIRAnalytics/ERROR> Cannot create String value with nil
<FIRAnalytics/ERROR> Inconsistent state, raw event is expected. Error: Error Domain=com.google.gmp.measurement.ErrorDomain Code=2 "Cannot create an event from database. Missing origin parameter" UserInfo={NSLocalizedDescription=Cannot create an event from database. Missing origin parameter}

**Comment by baolocdo** [comment] 2016-10-30 17:20
That's strange. What's the iOS version? Is this on a particular device or simulator? Can you uninstall your app from the device and reinstall again? There could be some corrupted data stored in the database. Thanks

**Comment by DmitryArbuzov** [comment] 2017-01-20 11:50
It's iOS version independent. Reinstalling app doesn't help.
I even don't send any event. Just [FIRApp configure];

**Comment by baolocdo** [comment] 2017-01-21 18:35
I haven't been successful in reproducing this issue so far. We will investigate this problem. Thanks for reporting.

**Comment by DmitryArbuzov** [comment] 2017-01-23 12:12
Sorry. You can close this issue.
Our's problem was in category NSObject, which overided its's functions.
Legacy code........

**Comment by morganchen12** [comment] 2017-01-23 20:58
Thanks for following up, @DmitryArbuzov!

**Comment by andwun** [comment] 2017-01-30 15:00
@DmitryArbuzov We're having the same problem. Were you able to track down the exact thing that caused this issue?

**Comment by DmitryArbuzov** [comment] 2017-01-30 15:03
@andwun In prefix.pch was imported NSObject and NSString categories, which added methods like "stringValue", "objectForKey:" etc.
I removed these categories from project, fixed places, which used this and issue gone.

**Comment by andwun** [comment] 2017-01-31 15:49
@DmitryArbuzov Thanks for the concrete details on the issue. Indeed we also had a method -[NSObject stringValue] added via a category that seemed to mess with the SDK. After renaming the method, the SDK now works as intended.

**Comment by baolocdo** [comment] 2017-02-03 06:00
That's great to know! Thanks for the detailed answer! I was pulling my hair out with this bug...

**Comment by nascimentorafael** [comment] 2017-03-03 18:16
I am having a similar issue here:

https://github.com/firebase/quickstart-ios/issues/229

**Comment by morganchen12** [comment] 2017-04-13 18:58
Closing this because inactivity and everyone seems to be responding with their own case-by-case similar issue.

**Closed by morganchen12** 2017-04-13 18:58 UTC
